### ISSUE TITLE
GNURadio 3.8 and Python 3 support

### ISSUE THREAD

**Issue by yarda** [Tom-McDermott/gr-hpsdr#13]
Hi,

Python 2 will be unsupported soon, so Linux distro's are dropping Python 2 packages. E.g. in Fedora Rawhide (f32) all Python 2 packages without FESCO exception have been mass orphaned.

GNURadio 3.8 is fully Python 3 compatible, but GNURadio modules have to be ported to it. In Fedora downstream we used the following patch [1]. It's not the cleanest solution, but it helped us to keep the gr-hpsdr in the distro. We will switch to the upstream solution once available.

[1] https://src.fedoraproject.org/rpms/gr-hpsdr/blob/master/f/gr-hpsdr-1.2-gnuradio38.patch

**Comment by Tom-McDermott** [comment]
Thank you for this, yarda !     It is going to be quite awhile until I can setup a new environment to install, test, and port the module to 3.8.  So this is very useful in the meantime.

**Comment by frohro** [comment]
Could we have this patch applied in a separate branch?  Ubuntu 20.04 is ditching python2 and uses GnuRadio 3.8.
Thanks,
Rob

**Comment by Tom-McDermott** [comment]
I have started the port to gnuradio 3.8 on Ubuntu 20.04  Will add a gr_3.7 branch and a gr_3.8 branch (and preserve master branch for legacy).

There appears to be several initial bugs in gr3.8 auto-generated OOT CMake, Make, and modules, so this is not going well right now.

Nothing has been pushed to github yet (since nothing works).  I will also add instructions on the workarounds needed s I find them.

-- Tom

**Comment by daniestevez** [comment]
Hi Tom,

A few days ago I ported [gr-hermeslite2](https://github.com/daniestevez/gr-hermeslite2) to GNU Radio 3.8. This is a fork of gr-hpsdr that contains some features specifics to the Hermes-Lite 2. Maybe you could find the port useful. Perhaps just copying the CMakeFiles from gr-hermeslite2 works, with little or no modifications, or you could look at the [commit](https://github.com/daniestevez/gr-hermeslite2/commit/e0b7422bc139a3f7519a00f98d7af305e921b376) itself.

**Comment by Tom-McDermott** [comment]
Thank you, Daniel.    Apparently the auto-generated Cmake and make files are no longer complete as they were in gr3.7.  Not being fluent in either CMake or make, I appreciate being able to look over your OOT. That should be invaluable.

-- Tom

**Comment by Tom-McDermott** [comment]
Hi Daniel - the autogenerateed CMake files are identical (except for hermes vs. hermeslite2).

I edited .bashrc to add pythonpath, when I try to launch from grc, it can't find the pythonpath, but launching from shell does.  That's wierd.

My modules instantiate correctly into grc.

After launching from shell, python does not find any methods defined for hermesNB.  I can look in the .so object file, and they're there, so somehow swig is not generating them.

Given the identicalness of all our CMake files, I am stumped.  I installed 20.04 and grc 3.8 from gnuradio-releases.  I did find one missing dependency in gnuradio  liborc-0.4-dev which was need to make sucessfully.   I'm running 3.8.1.0

-- Tom

**Comment by daniestevez** [comment]
Basically I created a new project with gr_modtool, copied the files over, and then adapted a few things. So no wonder that the CMake files are identical.

If you're launching gnuradio-companion from your Desktop Manager, it might happen that the Desktop Manager doesn't get its environment from .bashrc. Try launching gnuradio-companion from a shell in xterm or similar (if you haven't tried that yet).

Regarding Python not finding the methods, it might happen that the .so file is not in the correct path (did you run ldconfig?). Look into `__initi__.py` usually there is a `try` statement that silences errors opening the .so file.

I'm using debian testing and I also needed to install liborc-0.4-dev by hand. It seems it is a build dependency of all GNU Radio OOT modules, but not a runtime dependency of GNU Radio, so it doesn't get installed by default.

**Comment by Tom-McDermott** [comment]
Thanks, Daniel.     On Ubuntu 20.04,  your hunch was exactly right.   .bashrc only sends the environment variables to the shell. So launching grc from a terminal worked.  Turns out that the PATH edits need to go into ~/.profile  (then logout then login).  That populates gnome windows manager, from which grc (and bash) inherit the variables.  IIRC, this is different behavior than previous Linux system.

The missing methods was due to SWIG not being installed.

The what-one-needs-to-do list is getting longer.....

-- Tom, N5EG

**Comment by Tom-McDermott** [comment]
Thanks to Daniel Estevez for his help.    Gnuradio 3.8 / Ubuntu 20.04 support
is now available for testing.   Please use github issues if you experience 
any problems.
