### ISSUE TITLE
switching Common Mercury Frequency on

### ISSUE THREAD

**Issue by hanrod97** [Tom-McDermott/gr-hpsdr#15]
Hello,

i need to turn on the Common Mercury Frequency, which would be a one for the MSB of C4 while C0=0.
Is there a way of achieving that with the hermesNB or is there an easy way to change that in the code of gr-hpsdr? That would be awesome.

thank you and best regards,
Hannes

**Comment by Tom-McDermott** [comment]
Ok, found the protocol 1 documentation...    This will eventually require a new GUI element that will change the API. Before doing  implementing an API change, I've put together a quick test branch that just sets that individual bit to 1.     I do not have a Mercury board to test this so could you test that this temporary branch solves this ?   If so, then I can add a new GUI field to manage bits 7 and 6 on this register.

The branch is called:  TestMercClock
So ...
$ git checkout TestMercClock
then empty out the /build directory
then go through the normal cmake, make, install process...

-- Tom, N5EG

PS: this is for gnuradio 3.8

**Comment by hanrod97** [comment]
Hello,

thanks for the effort, sorry i was hoping there would be a more easy way. Unfortunately, i'm pretty new to Linux, GnuRadio and GitHub and i'm not sure if it worked. I'll just describe my problem a little bit more so you know what i'm trying to do:

I'm using a Red Pitaya 122.88-16 with GRC to measure phase shift between the two input signals. My problem was that they use different DDS for each input (see http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver-hpsdr-122-88/ ), so every time i change the center frequency in GRC, i'll get another phase. 
So i asked in another forum ( https://github.com/pavel-demin/red-pitaya-notes/issues/982 ) and got told i have to switch on the common mercury frequency and that's how i got here, i hope it's the right way of archieving constant phase measurements between the two inputs.

> Ok, found the protocol 1 documentation... This will eventually require a new GUI element that will change the API. Before doing implementing an API change, I've put together a quick test branch that just sets that individual bit to 1. I do not have a Mercury board to test this so could you test that this temporary branch solves this ? If so, then I can add a new GUI field to manage bits 7 and 6 on this register.

I'm trying but i may need some more information and guidance...

> The branch is called: TestMercClock
> So ...
> $ git checkout TestMercClock
> then empty out the /build directory

As far as i can tell it worked. I just had to clone the gr-hpsdr repository again, cause i installed from the .zip before... but it should nevertheless install the new branch to my GRC, shouldn't it?

> then go through the normal cmake, make, install process...

I did, i also did an 'sudo make uninstall' in between.

so now i tried measuring a phaseshift at 10MHz, switched to 100MHz and back again and i got a totally different Phaseshift (while leaving my assembly completely untouched) ... do i have to do it different or did it just not work?

> PS: this is for gnuradio 3.8
 I'm using GR3.8 thanks :-)

best regards,
Hannes

**Comment by Tom-McDermott** [comment]
Hi Hannes - thank you for the link to your discussion with Pavel to provide context. The Common Mercury Frequency synchronizes two receivers, not transmitter and receiver.  So this will not solve the problem you raised in that thread.

I suspect you correctly checked out the new test branch.  In git, if you attempt to checkout a non-existent branch, you will get an error message:
     error: pathspec <the_branchname_you_typed> did not match any file(s) known to git.

I am going to revert this test change (remove the TextMercClock branch) and close the issue.

-- Tom, N5EG

**Comment by hanrod97** [comment]
Hi Tom, 

i guess you got that wrong, i'm not using the transmitter of the red pitaya, i am using a frequency generator at the moment and two directional couplers attached to the inputs of the Red Pitaya. So i'd just need to synchronize the two inputs. Sorry for the confusion...

best regards,
Hannes

**Comment by Tom-McDermott** [comment]
Hi Hannes - OK.  I will leave the test branch attached to the code tree.

-- Tom, N5EG

**Comment by hanrod97** [comment]
Hi Tom, 

thank you very much!

i updated to the test branch as you said and i even replaced the hermesNB block with a new one but it doesn't work yet... do i have to do something else in addition or should it work yet?

best regards,
Hannes

**Comment by Tom-McDermott** [comment]
Hi Hannes - You should just be able to switch to the new branch, then rebuild, re-install, per the instructions.

When you say it doesn't work, do you mean that after rebuilding, gr-hpsdr does not work at all, or that
there is no change in behavior compared to the previous installation?

-- Tom, N5EG

**Comment by hanrod97** [comment]
yes i switched to the new branch, cleaned the build folder and reinstalled the TestMercClock.

There are no changes in the behavior of the hermesNB block.... as soon as i switch the center frequency i get a completely different phase difference between the two inputsignals.

-- Hannes

**Comment by Tom-McDermott** [comment]
HI Hannes - it sounds like you successfully installed the new test branch.  Unfortunately I cannot help much at this
point, the code sends the 1 bit in the Mercury Common Clock field, but I do not have a Red Pitaya, the FPGA code, the OpenHPSDR interface software for RP, or the hardware setup you have.  So there are multiple places where things could go wrong, but I can neither test them or debug them.

-- Tom, N5EG

**Comment by hanrod97** [comment]
Hi Tom,

ok that's unfortunate... anyway many thanks for your time and effort!

i'll try some more things with reinstalling gnu radio etc. and i'll let you know if it works. Meanwhile, could you please leave the testbranch online?

best regards,
Hannes

UPDATE: i indeed found something. When i open the program with preset 10MHz, i always measure the same phaseshift (so it works in this case), but if i change the frequency with a QT GUI Range Block during runtime it doesn't work anymore. 

Could you somehow implement that the hermesNB block updates the Common Mercury Frequency every time i update the center frequency?

**Comment by Tom-McDermott** [comment]
Hi Hannes - the Mercury Common Control bit is always sent as a one all the time.  I just verified this with a wireshark trace.

-- Tom, N5EG

**Comment by hanrod97** [comment]
Hi Tom,

ok i can't seem to make it work that way. Thanks for your time and effort, i'll try it differently with the Software on the RP

best regards,
Hannes
