### ISSUE TITLE
Please add support for gnuradio-3.9 which dropped swig

### ISSUE THREAD

**Issue by yarda** [Tom-McDermott/gr-hpsdr#16]
It seems gnuradio-3.9 dropped swig.

**Comment by Tom-McDermott** [comment]
I will put this item on my to-do list, but with no estimate of schedule yet.

My understanding is that currently the status of GR3.9 is somewhat limited:
there are issues with gr-modtool and the initial build repositories were just
announced a few days ago.

Folks on the mailing list have been asking for even a single working example
of a GR3.9 OOT module in the tutorials, perhaps that showed up in the last
couple days.

**Comment by yarda** [comment]
I used https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide for initial porting of some simple gr modules, but it's far from being good guide. Some upstream examples would definitely help with the process.

Gnuradio 3.9 is stable and we are trying to deploy it into Fedora Rawhide (f34).

**Comment by Tom-McDermott** [comment]
v3.0 has been added  (branch:  gr_3.9)  that supports gnuradio 3.9

Please note that pybind11 is very version-specific.   gnuradio 3.9.x installed
from the ppa was built against 2.5.0.    If you followed the gnuradio wiki and
installed pybind11 2.4.3 (from tarball) it won't work -- from tarball needs a manual removal.

Ubuntu 20.04 current pybind11-dev package points to 2.5.0
If you don't have pybind11-dev on your system :   $ sudo apt install pybind11-dev

**Comment by Tom-McDermott** [comment]
Am closing this issue.   Please open a new issue if there are problems, enhancements, etc. needed for gr_3.9
