### ISSUE TITLE
gr-hpsdr-3.0: strange sonames

### ISSUE THREAD

**Issue by yarda** [Tom-McDermott/gr-hpsdr#18]
The following files were created when building gr-hpsdr-3.0 (from the https://github.com/Tom-McDermott/gr-hpsdr/releases/tag/v3.0):
```
/usr/lib64/libgnuradio-hpsdr.so.1.0.0git
/usr/lib64/libgnuradio-hpsdr.so.v1.0-compat-xxx-xunknown
```

The 1.0.0git suffix is weird (especially for the stable release) but somehow acceptable, the v1.0-compat-xxx-xunknown is crazy.

**Comment by Tom-McDermott** [comment]
These are in /usr/libx86_64-linux-gnu/  on my system.

These are totally auto generated by the 3.9 OOT builder.  I have no control over how this gets done.

I have referred this question to the gnuradio list.

-- Tom, N5EG

**Comment by yarda** [comment]
It seems it's caused by the 'git' patch_level, changing it to the '0' fixes the problem for me:
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -33,7 +33,7 @@ list(INSERT CMAKE_MODULE_PATH 0 ${CMAKE_SOURCE_DIR}/cmake/Modules)
 set(VERSION_MAJOR 1)
 set(VERSION_API   0)
 set(VERSION_ABI   0)
-set(VERSION_PATCH git)
+set(VERSION_PATCH 0)
 
 cmake_policy(SET CMP0011 NEW)
 
```

**Comment by yarda** [comment]
I think it should be set to some number for the 'release'.

**Comment by Tom-McDermott** [comment]
I've received responses from the gnuradio list. The current generated softlinks are correct for a 'git' version patch.
If the patch version is changed to a number then the versioning would look more like what existing modules do.  This appears
to match Yarda's experience.   

Leaving the patch level at git would litter the library directory with git patch soft links which are not removed.
I will change to a numbered patch versioning scheme.   The advice from the list was a bit unclear about
the right way to do this, and exactly how this is cleaned up by Cmake.

**Comment by Tom-McDermott** [comment]
This has been pushed with VERSION_PATCH 0   from    VERSION_PATCH git.
On my system I needed to manually remove the older .so file and the softlink containing the git commit number:
In the appropriate directory for your library installation:
rm libgnuradio-hpsdr.so.e487bf33
rm libgnuradio-hpsdr.so.1.0.0git

I will endeavor to keep the gr_3.9 versioning up to date going forward.
Thanks for the feedback and advice!   I'll close this for now.

-- Tom
