### ISSUE TITLE
Timestamp send at beginning of stream and after overflow?

### ISSUE THREAD

**Issue by hb9ewy** [Tom-McDermott/gr-hpsdr#25]
Hello Tom, do these blocks send a timestamp with beginning of the stream and after any overflow?
I'm asking because when saving streams into a File Meta Sink the "rx_time" of the file header is always reading 0.0
Thanks for the great work.

**Comment by Tom-McDermott** [comment]
Hi Yves - the OpenHPSDR V1 protocol does not include a timestamp. It adds a 32-bit sequence number to each data packet emitted by the module.   The gr-hpsdr blocks look for skips in that sequence number to determine if there were lost receive packets.

The Hermes module implementation sends the data through FIFOs so timestamping at the Ethernet receiving computer would be quite inaccurate. The gr-hpsdr blocks do not add any timestamps.

-- Tom, N5EG

**Comment by hb9ewy** [comment]
Hi Tom, thank you, I should have know that. 
I'll need a timestamp with low accuracy requirements, in the range of seconds, so easy to find a workarround.
73, Yves hb9ewy
