### ISSUE TITLE
Error when typing make command on a Mac OS

### ISSUE THREAD

**Issue by samlo20** [Tom-McDermott/gr-hpsdr#5]
Hi Tom, 

This is the error I had when I followed the instructions on building the interface with HPSDR, 
and it shows after the 'make' command: 

/Users/ben/gr-hpsdr/lib/metis.cc:163:19: error: use of undeclared identifier
      'SIOCGIFHWADDR'
  if (ioctl(sock, SIOCGIFHWADDR, ifr) < 0) {
                  ^
1 error generated.
make[2]: *** [lib/CMakeFiles/gnuradio-hpsdr.dir/metis.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-hpsdr.dir/all] Error 2
make: *** [all] Error 2

and likewise the computer doesn't recognise this command too:

sudo ldconfig 

Is there any method to resolve these issue?

Thanks,
Sam

**Comment by Tom-McDermott** [comment]
Hi/

Sorry - I have never built this on a MAC, know nothing about MAC OS,
and do not have a MAC platform with which to try.

It needs someone who is literate in MAC to try.  A good reason to be
open-source.

-- Tom, N5EG
