### ISSUE TITLE
Soname for library

### ISSUE THREAD

**Issue by yarda** [Tom-McDermott/gr-hpsdr#7]
The library should have soname, for Fedora I added dummy one (0.0), but maybe the package version (1.2) should be used instead.

I added the soname by:
```
set_target_properties(gnuradio-hpsdr PROPERTIES SOVERSION 0)
set_target_properties(gnuradio-hpsdr PROPERTIES VERSION 0.0.0)
```
I could create pull request if needed.

**Comment by Tom-McDermott** [comment]
Thanks for the pull requests!  I need some education on this particular pull request.
Is this needed to solve a specific problem, or is it intended to be 'good practice'?
I find various library shared objects that do and don't follow this convention on my system.

-- Tom

**Comment by yarda** [comment]
I think it's good for both cases:

a) solving specific problem - it allows consumers of this library to work without recompilation while the soname version is compatible. Let's say you have 1.2.3 and you will fix some security problem in the code. Then you bump the soname version to 1.2.4 and all consumers of this library will work without recompilation (this is good for distros, because dependant packages don't need to be recompiled). But, if you change the API/ABI to be incompatible you bump the soname version to e.g. 2.0.0 and then all dependant packages will have to be updated and recompiled, because the dynamic linker will not load the library when 1.* is requested.

Also with versioning you can have multiple versions of the library installed (e.g. for experiments).

b) this is good practice. Some projects keep the soname same as the package version, i.e. MAJOR.MINOR.PATCH, some versions they API independently. Regarding Fedora there is a policy:
https://fedoraproject.org/wiki/Packaging:Guidelines#Downstream_.so_name_versioning
I guess other distros have something similar.

Usually the versioning is:
lib.so.X.Y.Z, where:
- X change means backwards incompatible ABI release
- Y change means backwards compatible ABI release
- Z change means Internal changes only - no change to the ABI
